publish_mode: editorial_workflow  # ✅ Active les drafts (brouillons) + PR

backend:
  name: github
  repo: RegistreSecurite/support_deemply
  branch: main
  base_url: https://support.deemply.com/admin-oauth  # ✅ Ton serveur PHP d’OAuth
  auth_endpoint: ""  # ✅ Important, évite /auth/auth

media_folder: docs/public/images  # ✅ Là où les images sont stockées dans le repo
public_folder: /images  # ✅ Là où elles seront visibles dans le site généré

collections:
  - name: 'guide'
    label: 'Guide'
    folder: 'docs/guide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true  # ✅ Active l’aperçu Markdown dans le CMS
    nested:
      depth: 10  # Profondeur maximale des sous-dossiers
      summary: '{{title}}'
    path: '{{folder}}/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { 
          label: 'Dossier', 
          name: 'folder', 
          widget: 'select',
          options: [
            { label: 'Registre de sécurité', value: 'safetyRegister' },
            { label: 'Registre de sécurité - Commission', value: 'safetyRegister/commission' },
            { label: 'Registre de sécurité - Employé', value: 'safetyRegister/employee' },
            { label: 'Registre de sécurité - Observation', value: 'safetyRegister/observation' },
            { label: 'Registre de sécurité - Prescription', value: 'safetyRegister/prescription' },
            { label: 'Registre de sécurité - Formation', value: 'safetyRegister/training' },
            { label: 'DUERP', value: 'duerp' },
            { label: 'Gestion des bâtiments', value: 'buildingManagement' },
            { label: "Registre d'accessibilité", value: 'accessibilityRegister' },
            { label: 'Entrées/Sorties', value: 'entriesExits' },
            { label: 'Permis de feu', value: 'firePermits' },
            { label: 'Plan de prévention', value: 'preventionPlan' },
            { label: 'Dossier médical', value: 'healthRecord' },
            { label: 'Formulaire', value: 'form' },
            { label: 'Core', value: 'core' },
            { label: 'Core - Activités', value: 'core/activities' },
            { label: 'Core - Interventions', value: 'core/interventions' },
            { label: 'Core - Matériels', value: 'core/materials' },
            { label: 'Core - Autres', value: 'core/others' },
            { label: 'Core - Fournisseurs', value: 'core/providers' },
            { label: 'Core - Sites', value: 'core/sites' },
            { label: 'Commun', value: 'common' }
          ]
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
