publish_mode: editorial_workflow  # ✅ Active les drafts (brouillons) + PR

backend:
  name: github
  repo: RegistreSecurite/support_deemply
  branch: main
  base_url: https://support.deemply.com  # ✅ Ton serveur PHP d’OAuth
  auth_endpoint: "admin-oauth/public/auth"  # ✅ Important, évite /auth/auth

media_folder: docs/public/images  # ✅ Là où les images sont stockées dans le repo
public_folder: /images  # ✅ Là où elles seront visibles dans le site généré

collections:
  - name: 'guide'
    label: 'Guide'
    folder: 'docs/guide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true  # ✅ Active l’aperçu Markdown dans le CMS
    nested:
      depth: 10  # Profondeur maximale des sous-dossiers
      summary: '{{title}}'
    path: '{{folder}}/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Ordre", name: "order", widget: "number", required: false }
      - { 
          label: 'Dossier', 
          name: 'folder', 
          widget: 'select',
          options: [
            { label: 'Fonctionnalités communes - Activités', value: 'fonctionnalités communes/1 - Activités' },
            { label: 'Fonctionnalités communes - Sites', value: 'fonctionnalités communes/2 - Sites' },
            { label: 'Fonctionnalités communes - Matériels', value: 'fonctionnalités communes/3 - Matériels' },
            { label: 'Fonctionnalités communes - Fournisseurs', value: 'fonctionnalités communes/4 - Fournisseurs' },
            { label: 'Fonctionnalités communes - Interventions', value: 'fonctionnalités communes/5 - Interventions' },
            { label: 'Fonctionnalités communes - Synthèses - Calendrier - Messages', value: 'fonctionnalités communes/6 - Synthèses - Calendrier - Messages' },
          ]
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }