publish_mode: editorial_workflow  # ✅ Active les drafts (brouillons) + PR

backend:
  name: github
  repo: RegistreSecurite/support_deemply
  branch: main
  base_url: https://support.deemply.com  # ✅ Ton serveur PHP d’OAuth
  auth_endpoint: "admin-oauth/public/auth"  # ✅ Important, évite /auth/auth

media_folder: docs/public/images  # ✅ Là où les images sont stockées dans le repo
public_folder: /images  # ✅ Là où elles seront visibles dans le site généré

collections:
  - name: 'core'
    label: 'Core'
    label_singular: 'Core'
    folder: _core
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - label: Title
        name: title
        widget: string
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

# collections:
#   - name: 'guide'
#     label: 'Guide'
#     folder: 'docs/guide'
#     create: true
#     slug: '{{slug}}'
#     editor:
#       preview: true  # ✅ Active l'aperçu Markdown dans le CMS
#     # Configuration pour les collections imbriquées
#     nested: { depth: 100, subfolders: false }
#     fields:
#       - { label: 'Title', name: 'title', widget: 'string' }
#       - { label: 'Description', name: 'description', widget: 'string' }
#       - { 
#           label: 'Dossier', 
#           name: 'folder', 
#           widget: 'select',
#           options: [
#             { label: 'Guide (racine)', value: '.' },
#             { label: 'Fonctionnalités communes', value: 'core' },
#             { label: 'Fonctionnalités communes - Activités', value: 'core/activities' },
#             { label: 'Fonctionnalités communes - Interventions', value: 'core/interventions' },
#             { label: 'Fonctionnalités communes - Matériels', value: 'core/materials' },
#             { label: 'Fonctionnalités communes - Autres', value: 'core/others' },
#             { label: 'Fonctionnalités communes - Fournisseurs', value: 'core/providers' },
#             { label: 'Fonctionnalités communes - Sites', value: 'core/sites' }
#           ]
#         }
#       - { label: 'Body', name: 'body', widget: 'markdown' }
#     meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
