publish_mode: editorial_workflow  # ✅ Active les drafts (brouillons) + PR

backend:
  name: github
  repo: RegistreSecurite/support_deemply
  branch: main
  base_url: https://support.deemply.com  # ✅ Ton serveur PHP d’OAuth
  auth_endpoint: "admin-oauth/public/auth"  # ✅ Important, évite /auth/auth

media_folder: docs/public/images  # ✅ Là où les images sont stockées dans le repo
public_folder: /images  # ✅ Là où elles seront visibles dans le site généré

collections:
  - name: 'guide'
    label: 'Guide'
    label_singular: 'Guide'
    folder: 'docs/guide'
    create: true
    editor:
      preview: true
    nested:
      depth: 100
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
    meta: { path: { widget: string, label: 'Path', index_file: '0' } }