publish_mode: editorial_workflow  # ✅ Active les drafts (brouillons) + PR

backend:
  name: github
  repo: RegistreSecurite/support_deemply
  branch: main
  base_url: https://support.deemply.com/admin-oauth  # ✅ Ton serveur PHP d’OAuth
  auth_endpoint: ""  # ✅ Important, évite /auth/auth

media_folder: docs/public/images  # ✅ Là où les images sont stockées dans le repo
public_folder: /images  # ✅ Là où elles seront visibles dans le site généré

collections:
  - name: 'guide'
    label: 'Guide'
    folder: 'docs/guide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true  # ✅ Active l’aperçu Markdown dans le CMS
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
