publish_mode: editorial_workflow  # ✅ Active les drafts (brouillons) + PR

backend:
  name: github
  repo: RegistreSecurite/support_deemply
  branch: main
  base_url: https://support.deemply.com  # ✅ Ton serveur PHP d’OAuth
  auth_endpoint: "admin-oauth/public/auth"  # ✅ Important, évite /auth/auth

media_folder: docs/public/images  # ✅ Là où les images sont stockées dans le repo
public_folder: /images  # ✅ Là où elles seront visibles dans le site généré

collections:
  - name: 'guide'
    label: 'Guide'
    folder: 'docs/guide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true  # ✅ Active l’aperçu Markdown dans le CMS
    nested:
      depth: 10  # Profondeur maximale des sous-dossiers
      summary: '{{title}}'
    path: '{{folder}}/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { 
          label: 'Dossier', 
          name: 'folder', 
          widget: 'select',
          options: [
            { label: 'Core', value: 'core' },
            { label: 'Core - Activités', value: 'core/activities' },
            { label: 'Core - Interventions', value: 'core/interventions' },
            { label: 'Core - Matériels', value: 'core/materials' },
            { label: 'Core - Autres', value: 'core/others' },
            { label: 'Core - Fournisseurs', value: 'core/providers' },
            { label: 'Core - Sites', value: 'core/sites' },
            { label: 'Commun', value: 'common' }
          ]
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }